/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package User;

import Admin.GetConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.ImageIcon;
import java.util.Date;
import javax.swing.JOptionPane;
import java.util.Random;
import Login.mainWindow;
/**
 *
 * @author ifzal
 */
public class HomeUser extends javax.swing.JFrame {

    /**
     * Creates new form HomeUser
     */
    public HomeUser() {
        initComponents();
    }
    int xMouse;
    int yMouse;
    float total = 0;
    static String user = "";
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        billbookid = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        billmoviename = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        billmoviedate = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        billbookingdate = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        billbookamount = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Dashboard = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        posterlabel1 = new javax.swing.JLabel();
        posterlabel2 = new javax.swing.JLabel();
        posterlabel3 = new javax.swing.JLabel();
        upcominglabel1 = new javax.swing.JLabel();
        upcominglabel2 = new javax.swing.JLabel();
        upcominglabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        moviename1 = new javax.swing.JLabel();
        moviename2 = new javax.swing.JLabel();
        moviename3 = new javax.swing.JLabel();
        upcomingmovie1 = new javax.swing.JLabel();
        upcomingmovie2 = new javax.swing.JLabel();
        upcomingmovie3 = new javax.swing.JLabel();
        SelectMoviePanel = new javax.swing.JPanel();
        backbtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        MovieInfoPanel = new javax.swing.JPanel();
        MoviePosterLabel = new javax.swing.JLabel();
        backbtn1 = new javax.swing.JButton();
        synopsislabel = new javax.swing.JLabel();
        Castlabel = new javax.swing.JLabel();
        directorlabel = new javax.swing.JLabel();
        producerlabel = new javax.swing.JLabel();
        releaselabel = new javax.swing.JLabel();
        languageslabel = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        TicketPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        ticketname = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        DateComboBox = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        ShowComboBox = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        SeatComboBox = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        seatcountcombo = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        totalamountlabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Mylabel = new javax.swing.JLabel();
        Mylabel1 = new javax.swing.JLabel();
        Mylabel2 = new javax.swing.JLabel();
        Mylabel3 = new javax.swing.JLabel();
        Mylabel4 = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        Firstlabel = new javax.swing.JLabel();
        Lastlabel = new javax.swing.JLabel();
        emaillabel = new javax.swing.JLabel();
        mobilelabel = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        bookticketmenubtn = new javax.swing.JMenuItem();
        acntinfomnubtn = new javax.swing.JMenuItem();
        bkdtcktshistbtn = new javax.swing.JMenuItem();
        logoutbtn = new javax.swing.JMenuItem();
        exitmenubtn = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jDialog1.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        jDialog1.setTitle("Generated Bill");
        jDialog1.setAlwaysOnTop(true);
        jDialog1.setBackground(new java.awt.Color(204, 0, 51));
        jDialog1.setLocation(new java.awt.Point(700, 300));
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(346, 465));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setText("Booking Id:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 36, 94, 36));

        billbookid.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(billbookid, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 36, 197, 36));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel11.setText("Movie:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 90, 94, 34));

        billmoviename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jPanel1.add(billmoviename, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 90, 193, 34));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel12.setText("Show Time:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 142, -1, 34));

        billmoviedate.setFont(jLabel10.getFont());
        jPanel1.add(billmoviedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 142, 193, 34));

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel13.setText("Booking Date:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 194, -1, 33));

        billbookingdate.setFont(jLabel10.getFont());
        jPanel1.add(billbookingdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 194, 193, 33));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel14.setText("Total Amount:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 245, -1, 34));

        billbookamount.setFont(jLabel10.getFont());
        jPanel1.add(billbookamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(153, 245, 193, 34));

        jLabel15.setFont(new java.awt.Font("Nueva Std", 0, 24)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("<html>Thank you for the Booking, Hope You Enjoy the Movie");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 325, 100));

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLayeredPane1.setBackground(new java.awt.Color(153, 0, 51));
        jLayeredPane1.setLayout(new java.awt.CardLayout());

        Dashboard.setBackground(new java.awt.Color(153, 0, 51));
        Dashboard.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                DashboardFocusGained(evt);
            }
        });
        Dashboard.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        jLabel1.setText("In Cinemas:");
        Dashboard.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 25, 181, 28));

        posterlabel1.setBackground(new java.awt.Color(0, 0, 0));
        posterlabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posterlabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                posterlabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                posterlabel1MouseExited(evt);
            }
        });
        Dashboard.add(posterlabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 180, 210));

        posterlabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posterlabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                posterlabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                posterlabel2MouseExited(evt);
            }
        });
        Dashboard.add(posterlabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 70, 180, 210));

        posterlabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                posterlabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                posterlabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                posterlabel3MouseExited(evt);
            }
        });
        Dashboard.add(posterlabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 70, 180, 210));

        upcominglabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upcominglabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upcominglabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upcominglabel1MouseExited(evt);
            }
        });
        Dashboard.add(upcominglabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 180, 210));

        upcominglabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upcominglabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upcominglabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upcominglabel2MouseExited(evt);
            }
        });
        Dashboard.add(upcominglabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 370, 180, 210));

        upcominglabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                upcominglabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                upcominglabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                upcominglabel3MouseExited(evt);
            }
        });
        Dashboard.add(upcominglabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 370, 180, 210));

        jLabel2.setFont(jLabel1.getFont());
        jLabel2.setText("Upcoming Movies:");
        Dashboard.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 200, -1));

        moviename1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moviename1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard.add(moviename1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 300, 160, 30));

        moviename2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moviename2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard.add(moviename2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 160, 30));

        moviename3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        moviename3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard.add(moviename3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 300, 160, 30));

        upcomingmovie1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard.add(upcomingmovie1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 600, 160, 30));

        upcomingmovie2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard.add(upcomingmovie2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 600, 160, 30));

        upcomingmovie3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard.add(upcomingmovie3, new org.netbeans.lib.awtextra.AbsoluteConstraints(774, 600, 160, 30));

        jLayeredPane1.add(Dashboard, "card2");

        SelectMoviePanel.setBackground(new java.awt.Color(153, 0, 51));

        backbtn.setBackground(new java.awt.Color(0, 0, 0));
        backbtn.setForeground(new java.awt.Color(255, 0, 51));
        backbtn.setText("Back");
        backbtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbtn.setBorderPainted(false);
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Orator Std", 1, 18)); // NOI18N
        jLabel3.setText("Select a movie");

        jComboBox1.setForeground(new java.awt.Color(255, 0, 51));
        jComboBox1.setMaximumRowCount(10);
        jComboBox1.setToolTipText("");
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setForeground(new java.awt.Color(255, 0, 51));
        jButton1.setText("Book Tickets");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SelectMoviePanelLayout = new javax.swing.GroupLayout(SelectMoviePanel);
        SelectMoviePanel.setLayout(SelectMoviePanelLayout);
        SelectMoviePanelLayout.setHorizontalGroup(
            SelectMoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectMoviePanelLayout.createSequentialGroup()
                .addGroup(SelectMoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(SelectMoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(SelectMoviePanelLayout.createSequentialGroup()
                            .addGap(30, 30, 30)
                            .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(SelectMoviePanelLayout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(589, Short.MAX_VALUE))
        );
        SelectMoviePanelLayout.setVerticalGroup(
            SelectMoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SelectMoviePanelLayout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76)
                .addGroup(SelectMoviePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(410, Short.MAX_VALUE))
        );

        jLayeredPane1.add(SelectMoviePanel, "card3");

        MovieInfoPanel.setBackground(new java.awt.Color(153, 0, 51));

        backbtn1.setBackground(new java.awt.Color(0, 0, 0));
        backbtn1.setForeground(new java.awt.Color(255, 0, 51));
        backbtn1.setText("Back");
        backbtn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        backbtn1.setBorderPainted(false);
        backbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtn1ActionPerformed(evt);
            }
        });

        synopsislabel.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        synopsislabel.setToolTipText("");
        synopsislabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        Castlabel.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N

        directorlabel.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N

        producerlabel.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N

        releaselabel.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N

        languageslabel.setFont(new java.awt.Font("Tekton Pro Cond", 0, 18)); // NOI18N

        jButton2.setBackground(new java.awt.Color(0, 0, 0));
        jButton2.setFont(new java.awt.Font("Stencil Std", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 0, 51));
        jButton2.setText("Book Now");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.setBorderPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MovieInfoPanelLayout = new javax.swing.GroupLayout(MovieInfoPanel);
        MovieInfoPanel.setLayout(MovieInfoPanelLayout);
        MovieInfoPanelLayout.setHorizontalGroup(
            MovieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovieInfoPanelLayout.createSequentialGroup()
                .addGroup(MovieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MovieInfoPanelLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(backbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(MovieInfoPanelLayout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addGroup(MovieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(MovieInfoPanelLayout.createSequentialGroup()
                                .addComponent(MoviePosterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addGroup(MovieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Castlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(directorlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(producerlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(releaselabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(languageslabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)))
                            .addComponent(synopsislabel, javax.swing.GroupLayout.PREFERRED_SIZE, 936, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        MovieInfoPanelLayout.setVerticalGroup(
            MovieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MovieInfoPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(MovieInfoPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(MovieInfoPanelLayout.createSequentialGroup()
                        .addComponent(Castlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(directorlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(producerlabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(releaselabel, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(languageslabel, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(MoviePosterLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(synopsislabel, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLayeredPane1.add(MovieInfoPanel, "card4");

        TicketPanel.setBackground(new java.awt.Color(153, 0, 51));

        jLabel4.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel4.setText("Movie Name:");

        ticketname.setEditable(false);
        ticketname.setBackground(new java.awt.Color(51, 51, 51));
        ticketname.setFont(new java.awt.Font("Tekton Pro Ext", 0, 14)); // NOI18N
        ticketname.setForeground(new java.awt.Color(255, 0, 51));

        jLabel5.setFont(new java.awt.Font("Sitka Heading", 0, 18)); // NOI18N
        jLabel5.setText("Select Date:");

        DateComboBox.setBackground(new java.awt.Color(51, 51, 51));

        jLabel6.setFont(jLabel5.getFont());
        jLabel6.setText("Select Show:");

        ShowComboBox.setBackground(new java.awt.Color(51, 51, 51));

        jButton3.setBackground(new java.awt.Color(0, 0, 0));
        jButton3.setForeground(new java.awt.Color(255, 0, 51));
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setBorderPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel7.setFont(jLabel5.getFont());
        jLabel7.setText("Seat Class:");

        SeatComboBox.setBackground(new java.awt.Color(51, 51, 51));
        SeatComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Gold-150/-", "Platinum-210/-", "Recliner-300/-" }));
        SeatComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeatComboBoxActionPerformed(evt);
            }
        });
        SeatComboBox.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                SeatComboBoxPropertyChange(evt);
            }
        });

        jLabel8.setFont(jLabel5.getFont());
        jLabel8.setText("No. of Seats");

        jButton4.setBackground(new java.awt.Color(0, 0, 0));
        jButton4.setFont(new java.awt.Font("Tekton Pro Ext", 1, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 0, 51));
        jButton4.setText("Book Tickets");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        seatcountcombo.setBackground(new java.awt.Color(51, 51, 51));
        seatcountcombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6" }));
        seatcountcombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatcountcomboActionPerformed(evt);
            }
        });

        jLabel9.setFont(jLabel5.getFont());
        jLabel9.setText("Total Amount:");

        totalamountlabel.setFont(new java.awt.Font("Tekton Pro Ext", 1, 11)); // NOI18N
        totalamountlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout TicketPanelLayout = new javax.swing.GroupLayout(TicketPanel);
        TicketPanel.setLayout(TicketPanelLayout);
        TicketPanelLayout.setHorizontalGroup(
            TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicketPanelLayout.createSequentialGroup()
                .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(TicketPanelLayout.createSequentialGroup()
                        .addGap(273, 273, 273)
                        .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(TicketPanelLayout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ticketname, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TicketPanelLayout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(TicketPanelLayout.createSequentialGroup()
                                .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ShowComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(SeatComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                    .addComponent(seatcountcombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(totalamountlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                    .addGroup(TicketPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(443, Short.MAX_VALUE))
        );
        TicketPanelLayout.setVerticalGroup(
            TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TicketPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107)
                .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ticketname, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ShowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(SeatComboBox)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(seatcountcombo)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(TicketPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalamountlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );

        jLayeredPane1.add(TicketPanel, "card5");

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel2MouseEntered(evt);
            }
        });

        Mylabel.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        Mylabel.setText("UserName:");

        Mylabel1.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        Mylabel1.setText("FirstName:");

        Mylabel2.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        Mylabel2.setText("LastName:");

        Mylabel3.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        Mylabel3.setText("Email Id:");

        Mylabel4.setFont(new java.awt.Font("Tekton Pro Cond", 0, 24)); // NOI18N
        Mylabel4.setText("Registered Mobile:");

        userLabel.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N
        userLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                userLabelMouseEntered(evt);
            }
        });

        Firstlabel.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N

        Lastlabel.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N

        emaillabel.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N

        mobilelabel.setFont(new java.awt.Font("Segoe Print", 0, 18)); // NOI18N

        jButton5.setBackground(new java.awt.Color(0, 0, 0));
        jButton5.setForeground(new java.awt.Color(255, 0, 51));
        jButton5.setText("Back");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Mylabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Firstlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Mylabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Lastlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Mylabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(emaillabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Mylabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(mobilelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(Mylabel, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(userLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(531, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mylabel, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Firstlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mylabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Lastlabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mylabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emaillabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Mylabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Mylabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                    .addComponent(mobilelabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(308, Short.MAX_VALUE))
        );

        jLayeredPane1.add(jPanel2, "card6");

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 660));

        jMenuBar1.setBackground(new java.awt.Color(0, 0, 0));

        jMenu1.setText("Account");

        bookticketmenubtn.setText("Book a movie");
        bookticketmenubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookticketmenubtnActionPerformed(evt);
            }
        });
        jMenu1.add(bookticketmenubtn);

        acntinfomnubtn.setText("Account Info");
        acntinfomnubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                acntinfomnubtnActionPerformed(evt);
            }
        });
        jMenu1.add(acntinfomnubtn);

        bkdtcktshistbtn.setText("Booked Tickets");
        jMenu1.add(bkdtcktshistbtn);

        logoutbtn.setText("Log Out");
        logoutbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbtnActionPerformed(evt);
            }
        });
        jMenu1.add(logoutbtn);

        exitmenubtn.setText("Exit");
        exitmenubtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitmenubtnActionPerformed(evt);
            }
        });
        jMenu1.add(exitmenubtn);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Extras");

        jMenuItem6.setText("About");
        jMenu2.add(jMenuItem6);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1056, 696));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitmenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitmenubtnActionPerformed
        System.exit(0);        // TODO add your handling code here:
    }//GEN-LAST:event_exitmenubtnActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        try{
         Class.forName("com.mysql.jdbc.Driver");
          Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinemadb","root","Bilal_1053");
          Statement st = con.createStatement();
          String pattern = "yyyy-MM-dd";
            SimpleDateFormat sdf = new SimpleDateFormat(pattern);
            String date = "'"+sdf.format(new Date())+"'";
          ResultSet rs1 = st.executeQuery("select MovieName,dashboardaddress from movietable where ReleaseDate <="+date+";");
          rs1.absolute(1);
          posterlabel1.setIcon(new ImageIcon(rs1.getString(2)));
          moviename1.setText(rs1.getString(1));
          rs1.absolute(2);
          posterlabel2.setIcon(new ImageIcon(rs1.getString(2)));
          moviename2.setText(rs1.getString(1));
          rs1.absolute(3);
          posterlabel3.setIcon(new ImageIcon(rs1.getString(2)));
          moviename3.setText(rs1.getString(1));
          
          
          ResultSet rs = st.executeQuery("select MovieName,dashboardaddress from movietable where ReleaseDate >"+date+";");
          rs.absolute(1);
          upcominglabel1.setIcon(new ImageIcon(rs.getString(2)));
          upcomingmovie1.setText(rs.getString(1));
          rs.absolute(2);
          upcominglabel2.setIcon(new ImageIcon(rs.getString(2)));
          upcomingmovie2.setText(rs.getString(1));
          rs.absolute(3);
          upcominglabel3.setIcon(new ImageIcon(rs.getString(2)));
          upcomingmovie3.setText(rs.getString(1));
          
     }catch(Exception e){
         System.out.println(e);
     }    // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void bookticketmenubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookticketmenubtnActionPerformed
    jLayeredPane1.removeAll();
    jComboBox1.removeAllItems();
    try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinemadb","root","Bilal_1053");
        String pattern = "yyyy-MM-dd";
            SimpleDateFormat sdf = new SimpleDateFormat(pattern);
            String date = "'"+sdf.format(new Date())+"'";
        String query = "Select * from movietable ";
        Statement st = con.createStatement();
        ResultSet rs = st.executeQuery(query);
        while(rs.next()){
            jComboBox1.addItem(rs.getString("MovieName"));
        }
    }catch(Exception e){
        System.out.println(e);
    }
    jLayeredPane1.add(SelectMoviePanel);
    repaint();
    revalidate();
// TODO add your handling code here:
    }//GEN-LAST:event_bookticketmenubtnActionPerformed

    private void seatcountcomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatcountcomboActionPerformed
        int val = SeatComboBox.getSelectedIndex();

        if(val == 0){
            total = 150 * Integer.parseInt(seatcountcombo.getSelectedItem().toString());
            totalamountlabel.setText(Float.toString(total));
        }else if(val == 1){
            total = 210 * Integer.parseInt(seatcountcombo.getSelectedItem().toString());
            totalamountlabel.setText(Float.toString(total));
        }else{
            total = 300 * Integer.parseInt(seatcountcombo.getSelectedItem().toString());
            totalamountlabel.setText(Float.toString(total));
        } // TODO add your handling code here:
    }//GEN-LAST:event_seatcountcomboActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int v = JOptionPane.showConfirmDialog(this, "DO YOU WANT TO CONFIRM YOUR BOOKING?");
        Random ran = new Random();
        String moviedatString = DateComboBox.getSelectedItem().toString()+", "+ShowComboBox.getSelectedItem().toString();
        int booking_id = 10000 + ran.nextInt(90000);
        String pattern = "yyyy-MM-dd";
        SimpleDateFormat sdf = new SimpleDateFormat(pattern);
        String date = sdf.format(new Date());
        if(v == JOptionPane.YES_OPTION){
            jDialog1.setVisible(true);
            billbookamount.setText(Float.toString(total));
            billbookid.setText(Integer.toString(booking_id));
            billbookingdate.setText(date);
            billmoviename.setText(jComboBox1.getSelectedItem().toString());
            billmoviedate.setText(moviedatString);
        }// TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void SeatComboBoxPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_SeatComboBoxPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_SeatComboBoxPropertyChange

    private void SeatComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeatComboBoxActionPerformed
        int val = SeatComboBox.getSelectedIndex();

        if(val == 0){
            total = 150 * Integer.parseInt(seatcountcombo.getSelectedItem().toString());
            totalamountlabel.setText(Float.toString(total));
        }else if(val == 1){
            total = 210 * Integer.parseInt(seatcountcombo.getSelectedItem().toString());
            totalamountlabel.setText(Float.toString(total));
        }else{
            total = 300 * Integer.parseInt(seatcountcombo.getSelectedItem().toString());
            totalamountlabel.setText(Float.toString(total));
        }
    }//GEN-LAST:event_SeatComboBoxActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        DateComboBox.removeAllItems();
        ShowComboBox.removeAllItems();
        jLayeredPane1.removeAll();
        jLayeredPane1.add(MovieInfoPanel);
        repaint();
        revalidate();  // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        String moviename = "'"+jComboBox1.getSelectedItem().toString()+"'";
        String showdates[];
        String dateout = "";
        float totalAmount = 0;

        String [] showtimings;
        ticketname.setText(jComboBox1.getSelectedItem().toString());
        String query1 = "select shows,showdates from showstable where moviename ="+moviename+"";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinemadb","root","Bilal_1053");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(query1);
            rs.absolute(1);
            showtimings = rs.getString("shows").split("\\|");
            showdates = rs.getString("showdates").split("\\|");
            for(String date:showdates){
                DateComboBox.addItem(date);
            }
            for(String show:showtimings){
                ShowComboBox.addItem(show);
            }
        }catch(Exception e){
            System.out.println(e);
        }

        jLayeredPane1.removeAll();
        jLayeredPane1.add(TicketPanel);
        repaint();
        revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void backbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtn1ActionPerformed

        jLayeredPane1.removeAll();
        jLayeredPane1.add(Dashboard);
        repaint();
        revalidate();
        // TODO add your handling code here:
    }//GEN-LAST:event_backbtn1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String moviename = "'"+jComboBox1.getSelectedItem().toString()+"'";
        String gquery = "select * from movietable where moviename = "+moviename+";";
        String syno = "<html>Synopsis:";
        String Rd = "Release Date:";
        String PName = "Produced By:";
        String DName = "Directed By:";
        String Lang = "Language:";
        String Cast = "Cast:";
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/cinemadb","root","Bilal_1053");
            Statement st = con.createStatement();
            ResultSet rs = st.executeQuery(gquery);
            rs.absolute(1);
            MoviePosterLabel.setIcon(new ImageIcon(rs.getString("posteraddress")));
            synopsislabel.setText(syno+rs.getString("Synopsis"));
            releaselabel.setText(Rd+rs.getString("ReleaseDate"));
            producerlabel.setText(PName+rs.getString("Producers"));
            directorlabel.setText(DName+rs.getString("directors"));
            languageslabel.setText(Lang+rs.getString("Languages"));
            Castlabel.setText(Cast+rs.getString("starcast"));

        }catch(Exception e){
            System.out.println(e);
        }
        jLayeredPane1.removeAll();
        jLayeredPane1.add(MovieInfoPanel);
        repaint();
        revalidate();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        jComboBox1.removeAllItems();
        jLayeredPane1.removeAll();
        jLayeredPane1.add(Dashboard);
        repaint();
        revalidate();// TODO add your handling code here:
    }//GEN-LAST:event_backbtnActionPerformed

    private void DashboardFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_DashboardFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_DashboardFocusGained

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
     jLayeredPane1.removeAll();
        jLayeredPane1.add(Dashboard);
        repaint();
        revalidate();   // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void acntinfomnubtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_acntinfomnubtnActionPerformed
        mainWindow mw = new mainWindow();
        user = mw.getUserName();
        System.out.println(user);
        jLayeredPane1.removeAll();
        jLayeredPane1.add(jPanel2);
        repaint();
        revalidate();   // TODO add your handling code here:
    }//GEN-LAST:event_acntinfomnubtnActionPerformed

    private void posterlabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posterlabel1MouseEntered
       posterlabel1.setSize(190, 220);
    }//GEN-LAST:event_posterlabel1MouseEntered

    private void posterlabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posterlabel1MouseExited
       posterlabel1.setSize(180, 210); // TODO add your handling code here:
    }//GEN-LAST:event_posterlabel1MouseExited

    private void posterlabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posterlabel2MouseEntered
        posterlabel2.setSize(190, 220);// TODO add your handling code here:
    }//GEN-LAST:event_posterlabel2MouseEntered

    private void posterlabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posterlabel2MouseExited
        posterlabel2.setSize(180, 210);// TODO add your handling code here:
    }//GEN-LAST:event_posterlabel2MouseExited

    private void posterlabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posterlabel3MouseEntered
        posterlabel3.setSize(190, 220);// TODO add your handling code here:
    }//GEN-LAST:event_posterlabel3MouseEntered

    private void posterlabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posterlabel3MouseExited
        posterlabel3.setSize(180, 210);        // TODO add your handling code here:
    }//GEN-LAST:event_posterlabel3MouseExited

    private void upcominglabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcominglabel1MouseClicked
       String movie = "'"+upcomingmovie1.getText()+"'";
        String movie1 = upcomingmovie1.getText();
        GetConnection gc = new GetConnection();
        String myquery = "select * from movietable where MovieName = "+movie+";";
        
        try{
        ResultSet res = gc.exQu(myquery);
        res.next();
        String syno = res.getString("Synopsis");
        String Rd = res.getString("ReleaseDate");
        String PName = res.getString("Producers");
        String DName = res.getString("directors");
        String Lang = res.getString("Languages");
        String Cast = res.getString("starcast");
        String poadd = res.getString("posteraddress");
            prepareMoviePanel(Rd, Lang, Cast, syno, PName, DName, poadd,movie1);
        }catch(Exception e){
            System.out.println(e);
        } // TODO add your handling code here:
    }//GEN-LAST:event_upcominglabel1MouseClicked

    private void upcominglabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcominglabel1MouseEntered
        upcominglabel1.setSize(190, 220);
    }//GEN-LAST:event_upcominglabel1MouseEntered

    private void upcominglabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcominglabel1MouseExited
        upcominglabel1.setSize(180, 210);
    }//GEN-LAST:event_upcominglabel1MouseExited

    private void upcominglabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcominglabel2MouseEntered
        upcominglabel2.setSize(190, 220);
    }//GEN-LAST:event_upcominglabel2MouseEntered

    private void upcominglabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcominglabel2MouseExited
        upcominglabel2.setSize(180, 210);
    }//GEN-LAST:event_upcominglabel2MouseExited

    private void upcominglabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcominglabel3MouseEntered
        upcominglabel3.setSize(190, 220);
    }//GEN-LAST:event_upcominglabel3MouseEntered

    private void upcominglabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcominglabel3MouseExited
        upcominglabel3.setSize(180, 210);
    }//GEN-LAST:event_upcominglabel3MouseExited

    private void posterlabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posterlabel1MouseClicked
        String movie = "'"+moviename1.getText()+"'";
        String movie1 = moviename1.getText();
        GetConnection gc = new GetConnection();
        String myquery = "select * from movietable where MovieName = "+movie+";";
        
        try{
        ResultSet res = gc.exQu(myquery);
        res.next();
        String syno = res.getString("Synopsis");
        String Rd = res.getString("ReleaseDate");
        String PName = res.getString("Producers");
        String DName = res.getString("directors");
        String Lang = res.getString("Languages");
        String Cast = res.getString("starcast");
        String poadd = res.getString("posteraddress");
            prepareMoviePanel(Rd, Lang, Cast, syno, PName, DName, poadd,movie1);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_posterlabel1MouseClicked

    private void posterlabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posterlabel2MouseClicked
        String movie = "'"+moviename2.getText()+"'";
        String movie1 = moviename2.getText();
        GetConnection gc = new GetConnection();
        String myquery = "select * from movietable where MovieName = "+movie+";";
        
        try{
        ResultSet res = gc.exQu(myquery);
        res.next();
        String syno = res.getString("Synopsis");
        String Rd = res.getString("ReleaseDate");
        String PName = res.getString("Producers");
        String DName = res.getString("directors");
        String Lang = res.getString("Languages");
        String Cast = res.getString("starcast");
        String poadd = res.getString("posteraddress");
            prepareMoviePanel(Rd, Lang, Cast, syno, PName, DName, poadd,movie1);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_posterlabel2MouseClicked

    private void posterlabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posterlabel3MouseClicked
       String movie = "'"+moviename3.getText()+"'";
        String movie1 = moviename3.getText();
        GetConnection gc = new GetConnection();
        String myquery = "select * from movietable where MovieName = "+movie+";";
        
        try{
        ResultSet res = gc.exQu(myquery);
        res.next();
        String syno = res.getString("Synopsis");
        String Rd = res.getString("ReleaseDate");
        String PName = res.getString("Producers");
        String DName = res.getString("directors");
        String Lang = res.getString("Languages");
        String Cast = res.getString("starcast");
        String poadd = res.getString("posteraddress");
            prepareMoviePanel(Rd, Lang, Cast, syno, PName, DName, poadd,movie1);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_posterlabel3MouseClicked

    private void upcominglabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcominglabel2MouseClicked
        String movie = "'"+upcomingmovie2.getText()+"'";
        String movie1 = upcomingmovie2.getText();
        GetConnection gc = new GetConnection();
        String myquery = "select * from movietable where MovieName = "+movie+";";
        
        try{
        ResultSet res = gc.exQu(myquery);
        res.next();
        String syno = res.getString("Synopsis");
        String Rd = res.getString("ReleaseDate");
        String PName = res.getString("Producers");
        String DName = res.getString("directors");
        String Lang = res.getString("Languages");
        String Cast = res.getString("starcast");
        String poadd = res.getString("posteraddress");
            prepareMoviePanel(Rd, Lang, Cast, syno, PName, DName, poadd,movie1);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_upcominglabel2MouseClicked

    private void upcominglabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_upcominglabel3MouseClicked
        String movie = "'"+upcomingmovie3.getText()+"'";
        String movie1 = upcomingmovie3.getText();
        GetConnection gc = new GetConnection();
        String myquery = "select * from movietable where MovieName = "+movie+";";
        
        try{
        ResultSet res = gc.exQu(myquery);
        res.next();
        String syno = res.getString("Synopsis");
        String Rd = res.getString("ReleaseDate");
        String PName = res.getString("Producers");
        String DName = res.getString("directors");
        String Lang = res.getString("Languages");
        String Cast = res.getString("starcast");
        String poadd = res.getString("posteraddress");
            prepareMoviePanel(Rd, Lang, Cast, syno, PName, DName, poadd,movie1);
        }catch(Exception e){
            System.out.println(e);
        }
    }//GEN-LAST:event_upcominglabel3MouseClicked

    private void userLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userLabelMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_userLabelMouseEntered

    private void jPanel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseEntered
       try{
           GetConnection gc = new GetConnection();
           mainWindow mw = new mainWindow();
           String user = "'"+mw.getUserName()+"'";
           String query = "select * from userinfo where username = "+user+";";
           ResultSet res = gc.exQu(query);
           res.next();
           userLabel.setText(res.getString("username"));
           Firstlabel.setText(res.getString("first_name"));
           Lastlabel.setText(res.getString("last_name"));
           emaillabel.setText(res.getString("email"));
           mobilelabel.setText(res.getString("phone"));
       }catch(Exception e){
           System.out.println(e);
       }
    }//GEN-LAST:event_jPanel2MouseEntered

    private void logoutbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbtnActionPerformed
     jLayeredPane1.removeAll();
     String args[] = new String[WIDTH];
     mainWindow.main(args);
     dispose();// TODO add your handling code here:
    }//GEN-LAST:event_logoutbtnActionPerformed

    public void prepareMoviePanel(String reldt,String lang,String star,String Syno,String pro,String dir,String add,String movie){
        MoviePosterLabel.setIcon(new ImageIcon(add));
        synopsislabel.setText("<html>Synopsis:"+Syno);
        directorlabel.setText("Directed By:"+dir);
        producerlabel.setText("Produced By:"+pro);
        Castlabel.setText("Cast:"+star);
        releaselabel.setText("Release Date:"+reldt);
        jComboBox1.addItem(movie);
        jComboBox1.setSelectedItem(movie);
        jLayeredPane1.removeAll();
        jLayeredPane1.add(MovieInfoPanel);
        repaint();
        revalidate();
   }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeUser.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeUser().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Castlabel;
    private javax.swing.JPanel Dashboard;
    private javax.swing.JComboBox<String> DateComboBox;
    private javax.swing.JLabel Firstlabel;
    private javax.swing.JLabel Lastlabel;
    private javax.swing.JPanel MovieInfoPanel;
    private javax.swing.JLabel MoviePosterLabel;
    private javax.swing.JLabel Mylabel;
    private javax.swing.JLabel Mylabel1;
    private javax.swing.JLabel Mylabel2;
    private javax.swing.JLabel Mylabel3;
    private javax.swing.JLabel Mylabel4;
    private javax.swing.JComboBox<String> SeatComboBox;
    private javax.swing.JPanel SelectMoviePanel;
    private javax.swing.JComboBox<String> ShowComboBox;
    private javax.swing.JPanel TicketPanel;
    private javax.swing.JMenuItem acntinfomnubtn;
    private javax.swing.JButton backbtn;
    private javax.swing.JButton backbtn1;
    private javax.swing.JLabel billbookamount;
    private javax.swing.JLabel billbookid;
    private javax.swing.JLabel billbookingdate;
    private javax.swing.JLabel billmoviedate;
    private javax.swing.JLabel billmoviename;
    private javax.swing.JMenuItem bkdtcktshistbtn;
    private javax.swing.JMenuItem bookticketmenubtn;
    private javax.swing.JLabel directorlabel;
    private javax.swing.JLabel emaillabel;
    private javax.swing.JMenuItem exitmenubtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel languageslabel;
    private javax.swing.JMenuItem logoutbtn;
    private javax.swing.JLabel mobilelabel;
    private javax.swing.JLabel moviename1;
    private javax.swing.JLabel moviename2;
    private javax.swing.JLabel moviename3;
    public javax.swing.JLabel posterlabel1;
    public javax.swing.JLabel posterlabel2;
    public javax.swing.JLabel posterlabel3;
    private javax.swing.JLabel producerlabel;
    private javax.swing.JLabel releaselabel;
    private javax.swing.JComboBox<String> seatcountcombo;
    private javax.swing.JLabel synopsislabel;
    private javax.swing.JTextField ticketname;
    private javax.swing.JLabel totalamountlabel;
    public javax.swing.JLabel upcominglabel1;
    public javax.swing.JLabel upcominglabel2;
    public javax.swing.JLabel upcominglabel3;
    private javax.swing.JLabel upcomingmovie1;
    private javax.swing.JLabel upcomingmovie2;
    private javax.swing.JLabel upcomingmovie3;
    private javax.swing.JLabel userLabel;
    // End of variables declaration//GEN-END:variables
}
